# Generated by Django 3.1.2 on 2021-02-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_shape', models.CharField(max_length=30)),
                ('product_size', models.FloatField()),
                ('product_location', models.CharField(max_length=30)),
                ('product_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
            ],
        ),
    ]
