# Generated by Django 3.1.2 on 2021-02-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210219_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
